import { Link, useRouterState } from "@tanstack/react-router";
import { Bell, BriefcaseBusiness, ChartNoAxesCombined, ChevronDown, CircleDollarSign, ClipboardCheck, FileBarChart, LayoutDashboard, Menu, Search, Settings, SlidersHorizontal, Users, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { Tone } from "@/data/mock";
import { cn } from "@/lib/utils";
const nav=[
 {to:"/",label:"Dashboard",icon:LayoutDashboard,group:"Operação"}, {to:"/clientes",label:"Clientes",icon:BriefcaseBusiness}, {to:"/financeiro",label:"Financeiro",icon:CircleDollarSign}, {to:"/trafego",label:"Gestor de Tráfego",icon:ChartNoAxesCombined}, {to:"/relatorios",label:"Relatórios",icon:FileBarChart},
 {to:"/tarefas",label:"Gestão de Tarefas",icon:ClipboardCheck,group:"Gestão"}, {to:"/equipe",label:"Equipe",icon:Users}, {to:"/configuracoes",label:"Configurações",icon:Settings},
] as const;
export function AppShell({children}:{children:ReactNode}){const [mobile,setMobile]=useState(false); const [notices,setNotices]=useState(false); const pathname=useRouterState({select:s=>s.location.pathname}); return <div className="min-h-screen bg-background text-foreground md:flex">
 <aside className={cn("fixed inset-y-0 left-0 z-40 flex w-60 flex-col border-r border-border bg-sidebar transition-transform md:sticky md:translate-x-0",mobile?"translate-x-0":"-translate-x-full")}>
  <div className="flex h-14 items-center border-b border-border px-4"><Link to="/" className="flex items-center gap-2.5"><span className="grid size-7 place-items-center rounded-md bg-primary text-xs font-bold text-primary-foreground">V</span><span><b className="block text-sm leading-none">Vyon</b><small className="mt-1 block text-[9px] uppercase text-muted-foreground">Performance OS</small></span></Link><Button variant="ghost" size="icon" className="ml-auto md:hidden" onClick={()=>setMobile(false)} aria-label="Fechar menu"><X/></Button></div>
  <nav className="flex-1 overflow-y-auto px-3 py-4">{nav.map((item,i)=>{const active=item.to==="/"?pathname==="/":pathname.startsWith(item.to);const I=item.icon;return <div key={item.to}>{item.group&&<p className={cn("px-2 pb-1.5 text-[10px] font-semibold uppercase text-faint",i>0&&"pt-5")}>{item.group}</p>}<Link to={item.to} onClick={()=>setMobile(false)} className={cn("mb-0.5 flex items-center gap-2.5 rounded-md px-2.5 py-2 text-[13px] font-medium transition-colors",active?"bg-primary/10 text-primary":"text-sidebar-foreground hover:bg-accent hover:text-foreground")}><I className="size-4"/>{item.label}</Link></div>})}</nav>
  <div className="border-t border-border p-3"><div className="flex items-center gap-2.5 rounded-md p-2"><span className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-semibold">MC</span><span className="min-w-0 flex-1"><b className="block truncate text-xs">Marina Costa</b><small className="block truncate text-[10px] text-muted-foreground">Head de Operações</small></span><ChevronDown className="size-3.5 text-muted-foreground"/></div></div>
 </aside>{mobile&&<button className="fixed inset-0 z-30 bg-overlay md:hidden" onClick={()=>setMobile(false)} aria-label="Fechar menu"/>}
 <div className="min-w-0 flex-1"><header className="sticky top-0 z-20 flex h-14 items-center border-b border-border bg-background/95 px-4 backdrop-blur md:px-6"><Button variant="ghost" size="icon" className="mr-2 md:hidden" onClick={()=>setMobile(true)} aria-label="Abrir menu"><Menu/></Button><span className="text-xs text-muted-foreground">Vyon <span className="px-1 text-faint">/</span> <b className="font-medium text-foreground">{pageName(pathname)}</b></span><div className="ml-auto flex items-center gap-2"><div className="relative hidden sm:block"><Search className="absolute left-2.5 top-2 size-3.5 text-muted-foreground"/><Input aria-label="Busca global" className="h-8 w-64 pl-8 text-xs" placeholder="Buscar cliente, conta, tarefa…"/></div><Button variant="outline" size="icon" className="relative h-8 w-8" onClick={()=>setNotices(!notices)} aria-label="Notificações"><Bell className="size-3.5"/><span className="absolute -right-1 -top-1 grid size-4 place-items-center rounded-full bg-destructive text-[9px] text-destructive-foreground">5</span></Button></div></header>
 {notices&&<div className="fixed right-5 top-16 z-50 w-[360px] max-w-[calc(100vw-2rem)] overflow-hidden rounded-lg border border-border bg-popover shadow-xl"><div className="border-b border-border px-4 py-3"><b className="text-sm">Notificações</b><p className="text-xs text-muted-foreground">5 itens não lidos</p></div>{["Contrato da Alphora foi assinado","Cobrança da Gamma está vencida","Boreal aguarda dois acessos","Tarefa urgente atribuída a você","Relatório da Kora aguarda envio"].map((x,i)=><div className="border-b border-border px-4 py-3 text-xs" key={x}><b>{x}</b><p className="mt-1 text-muted-foreground">{i+1}h atrás</p></div>)}</div>}
 <main className="mx-auto max-w-[1600px] p-4 md:p-6">{children}</main></div></div>}
function pageName(path:string){if(path.startsWith("/clientes/novo"))return "Novo cliente";if(path.startsWith("/clientes/"))return "Visão 360º";return nav.find(n=>n.to!=="/"&&path.startsWith(n.to))?.label??"Dashboard"}
export function PageHeader({title,description,actions}:{title:string;description?:string;actions?:ReactNode}){return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">{title}</h1>{description&&<p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}
const tones:Record<Tone,string>={success:"bg-success/12 text-success",warning:"bg-warning/12 text-warning",danger:"bg-destructive/12 text-destructive",info:"bg-info/12 text-info",neutral:"bg-secondary text-muted-foreground"};
export function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:Tone}){return <span className={cn("inline-flex items-center gap-1.5 whitespace-nowrap rounded-full px-2 py-0.5 text-[11px] font-medium",tones[tone])}><span className="size-1.5 rounded-full bg-current"/>{children}</span>}
export function MetricStrip({items}:{items:{label:string;value:string;note?:string;tone?:Tone}[]}){return <div className="grid overflow-hidden rounded-lg border border-border bg-border sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">{items.map(x=><div className="bg-card px-4 py-3" key={x.label}><p className="text-[11px] text-muted-foreground">{x.label}</p><p className={cn("mt-1 text-xl font-semibold tabular-nums",x.tone&&tones[x.tone].split(" ")[1])}>{x.value}</p>{x.note&&<p className="mt-0.5 text-[11px] text-muted-foreground">{x.note}</p>}</div>)}</div>}
export function Filters({search="Buscar…",children}:{search?:string;children?:ReactNode}){return <div className="mb-4 flex flex-wrap items-center gap-2"><div className="relative min-w-56 flex-1 sm:max-w-xs"><Search className="absolute left-3 top-2.5 size-3.5 text-muted-foreground"/><Input className="pl-9" placeholder={search}/></div><Button variant="outline" size="sm"><SlidersHorizontal/>Filtros</Button>{children}</div>}
export function TableShell({children}:{children:ReactNode}){return <div className="overflow-x-auto rounded-lg border border-border bg-card">{children}</div>}
export function EmptyState({title,description}:{title:string;description:string}){return <div className="rounded-lg border border-dashed border-border px-6 py-12 text-center"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div>}
